name = "NetCDF_Examples"
version = "0.1.0"
license = "GPL v3"
author = "Paul Gierz"
maintainer = "paul.gierz@awi.de"
copyright = "Copyright 2022, Paul Gierz"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
